<?php
require_once('core/AbstractModel.php');

class Pokemon extends AbstractModel {

    protected string $tableName = 'pokemon';

    private int $id;

    private string $name;

    private string $types;

    public function __construct()
    {

    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getTypes()
    {
        return $this->types;
    }

    /**
     * @param mixed $types
     */
    public function setTypes($types)
    {
        $this->types = $types;
    }

    public function __toString()
    {
        return $this->name;
    }

    public function findAll(string $columns = '', string $inner = null,
                            string $condition = null, string $groupBy = null,
                            string $order = null, int $limit = null,
                            int $offset = null)
    {

        return parent::findAll( "pokemon.* , group_concat(DISTINCT T.label ORDER BY T.label DESC SEPARATOR ',') as types", 'INNER JOIN pokemon_has_type as PHT ON PHT.pokemon_id = pokemon.id 
        INNER JOIN type as T ON PHT.type_id = T.id', null, 'pokemon.id, pokemon.name');
    }

    public function findOneById($id, string $columns = '*', string $inner = null, string $groupBy = null)
    {
        return parent::findOneById($id, "pokemon.* , group_concat(DISTINCT T.label ORDER BY T.label DESC SEPARATOR ',') as types",
            "INNER JOIN pokemon_has_type as PHT ON PHT.pokemon_id = pokemon.id 
        INNER JOIN type as T ON PHT.type_id = T.id"); // TODO: Change the autogenerated stub
    }

    public function save($data)
    {
        if (empty($data["id"])){
            parent::save(array_slice($data, 0, 1));

            if (!empty($data["types"])){
                foreach ($data["types"] as $type)  {

                    $sql = ' INSERT INTO pokemon_has_type (pokemon_id, type_id)';
                    $sql .= ' SELECT id,'.$type.' FROM pokemon where name="'.$data["name"].'";';
                    self::createQuery($sql, get_class($this));
                }
            }
        }
        else {
            if (!empty($data["types"])){
                parent::save(array_slice($data, 0, 2));

                foreach ($data["types"] as $type)  {
                    $sql = ' UPDATE pokemon_has_type SET type_id='.$type.' WHERE pokemon_id='.$data["id"];
                    self::createQuery($sql, get_class($this));
                }
            } else {
                parent::save($data);
            }

        }
    }
}
